// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNc6Yd__szTfstF6hAK7PwgjMWa4tl6oE',
    appId: '1:713639140056:android:672f3124c68109336015ad',
    messagingSenderId: '713639140056',
    projectId: 'ecommerce-project-2025',
    storageBucket: 'ecommerce-project-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWk15Qn6EvlOMXN4DImvalYbC8Fw3kaMA',
    appId: '1:713639140056:ios:9b5b608afffe8ba16015ad',
    messagingSenderId: '713639140056',
    projectId: 'ecommerce-project-2025',
    storageBucket: 'ecommerce-project-2025.firebasestorage.app',
    androidClientId:
        '713639140056-udisevdgikp5r2tfp7pev3k65tp468uj.apps.googleusercontent.com',
    iosClientId:
        '713639140056-denn29e0cbjm3tem9mo4p2ak6ekqq7hg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterECommerceApp2025',
  );
}
